version: "3.8"

services:
  # MySQL Database (same as production)
  db:
    image: mysql:8.0
    container_name: ptsmart-crm-db-dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql_dev_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ptsmart-dev-network

  # Laravel Backend (Development mode with volume mounts)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ptsmart-crm-backend-dev
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - ptsmart-dev-network
    command: php artisan serve --host=0.0.0.0 --port=8000

  # React Frontend (Development mode with hot reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ptsmart-crm-frontend-dev
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ptsmart-dev-network
    command: npm start

  # Redis
  redis:
    image: redis:7-alpine
    container_name: ptsmart-crm-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ptsmart-dev-network

  # Mailpit (for email testing)
  mailpit:
    image: axllent/mailpit
    container_name: ptsmart-crm-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - ptsmart-dev-network

volumes:
  mysql_dev_data:
    driver: local

networks:
  ptsmart-dev-network:
    driver: bridge
