version: "3.8"

services:
    # Laravel Application
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ptsmart-crm-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - "8000:80"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=ptsmart_crm
            - DB_USERNAME=ptsmart_user
            - DB_PASSWORD=ptsmart_password
            - APP_NAME=PT Smart CRM
            - APP_ENV=production
            - APP_KEY=base64:$(openssl rand -base64 32)
            - APP_DEBUG=false
            - APP_URL=http://localhost:8000
            - CACHE_DRIVER=redis
            - SESSION_DRIVER=redis
            - QUEUE_CONNECTION=redis
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379
        depends_on:
            - db
            - redis
        networks:
            - ptsmart-network

    # MySQL Database
    db:
        image: mysql:8.0
        container_name: ptsmart-crm-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ptsmart_crm
            MYSQL_USER: ptsmart_user
            MYSQL_PASSWORD: ptsmart_password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3306:3306"
        networks:
            - ptsmart-network

    # Redis for Caching and Sessions
    redis:
        image: redis:7-alpine
        container_name: ptsmart-crm-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - ptsmart-network

    # Nginx Reverse Proxy (Optional)
    nginx:
        image: nginx:alpine
        container_name: ptsmart-crm-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./storage/logs:/var/log/nginx
        depends_on:
            - app
        networks:
            - ptsmart-network

    # Mailpit for Email Testing (Development)
    mailpit:
        image: axllent/mailpit
        container_name: ptsmart-crm-mailpit
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "8025:8025"
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - ptsmart-network

volumes:
    db_data:
        driver: local
    redis_data:
        driver: local

networks:
    ptsmart-network:
        driver: bridge
